"""
Job positions and their relevant skills database
Contains 40-50 skills for each job position
"""

# List of common job positions
common_positions = [
    'Software Developer',
    'Software Engineer',
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'Mobile Developer',
    'DevOps Engineer',
    'Data Scientist',
    'Data Analyst',
    'Data Engineer',
    'Machine Learning Engineer',
    'AI Engineer',
    'Product Manager',
    'Project Manager',
    'UI/UX Designer',
    'Graphic Designer',
    'Web Designer',
    'Business Analyst',
    'Quality Assurance Engineer',
    'QA Tester',
    'System Administrator',
    'Network Engineer',
    'Security Engineer',
    'Cloud Engineer',
    'Database Administrator',
    'Technical Writer',
    'Scrum Master',
    'Marketing Manager',
    'Sales Manager',
    'Customer Success Manager',
    'HR Manager',
    'Financial Analyst',
    'Accountant',
    'Content Writer',
    'SEO Specialist',
    'Digital Marketing Specialist',
]

# Skills database for each job position (40-50 skills each)
job_skills = {
    'software developer': [
        'JavaScript', 'TypeScript', 'Python', 'Java', 'C++', 'C#', 'Go', 'Ruby', 'PHP', 'Swift',
        'Kotlin', 'Rust', 'Scala', 'React', 'Angular', 'Vue.js', 'Node.js', 'Express', 'Django',
        'Flask', 'Spring Boot', 'ASP.NET', 'Git', 'GitHub', 'GitLab', 'Docker', 'Kubernetes',
        'AWS', 'Azure', 'Google Cloud', 'REST APIs', 'GraphQL', 'SQL', 'MongoDB', 'PostgreSQL',
        'MySQL', 'Redis', 'HTML5', 'CSS3', 'Sass', 'Less', 'Webpack', 'Vite', 'Jest', 'Mocha',
        'Pytest', 'JUnit', 'Testing', 'TDD', 'CI/CD',
    ],

    'software engineer': [
        'JavaScript', 'TypeScript', 'Python', 'Java', 'C++', 'C#', 'Go', 'Rust', 'Scala',
        'Git', 'Algorithms', 'Data Structures', 'System Design', 'Object-Oriented Programming',
        'Functional Programming', 'Design Patterns', 'SOLID Principles', 'Testing', 'Unit Testing',
        'Integration Testing', 'Debugging', 'Profiling', 'Code Review', 'Agile', 'Scrum', 'Kanban',
        'Problem Solving', 'CI/CD', 'Jenkins', 'Docker', 'Kubernetes', 'AWS', 'Azure', 'Microservices',
        'REST APIs', 'GraphQL', 'SQL', 'NoSQL', 'Database Design', 'Performance Optimization',
        'Security Best Practices', 'Code Documentation', 'Technical Communication', 'Pair Programming',
        'Refactoring', 'Version Control', 'Software Architecture', 'API Design', 'Distributed Systems',
    ],

    'full stack developer': [
        'JavaScript', 'TypeScript', 'HTML5', 'CSS3', 'React', 'Angular', 'Vue.js', 'Next.js',
        'Node.js', 'Express', 'NestJS', 'Python', 'Django', 'Flask', 'FastAPI', 'MongoDB',
        'PostgreSQL', 'MySQL', 'Redis', 'REST APIs', 'GraphQL', 'Docker', 'Kubernetes', 'AWS',
        'Azure', 'Google Cloud', 'Git', 'GitHub Actions', 'CI/CD', 'Agile', 'Testing', 'Jest',
        'Cypress', 'Selenium', 'Webpack', 'Vite', 'Responsive Design', 'UI/UX Principles',
        'Authentication', 'OAuth', 'JWT', 'WebSockets', 'Microservices', 'API Design', 'Database Design',
        'Performance Optimization', 'Security', 'DevOps', 'Linux', 'Nginx', 'Load Balancing',
    ],

    'frontend developer': [
        'JavaScript', 'TypeScript', 'HTML5', 'CSS3', 'React', 'Redux', 'React Hooks', 'Context API',
        'Vue.js', 'Vuex', 'Angular', 'RxJS', 'Sass', 'Less', 'Styled Components', 'CSS Modules',
        'Tailwind CSS', 'Bootstrap', 'Material-UI', 'Ant Design', 'Webpack', 'Vite', 'Babel',
        'ESLint', 'Prettier', 'Responsive Design', 'Mobile-First Design', 'CSS Grid', 'Flexbox',
        'Animations', 'UI/UX Principles', 'Accessibility', 'WCAG', 'ARIA', 'SEO', 'Web Performance',
        'Lighthouse', 'Git', 'npm', 'Yarn', 'Testing', 'Jest', 'React Testing Library', 'Cypress',
        'Cross-browser Compatibility', 'Progressive Web Apps', 'Service Workers', 'Web APIs',
    ],

    'backend developer': [
        'Node.js', 'Python', 'Java', 'C#', 'Go', 'Ruby', 'PHP', 'Express', 'NestJS', 'Django',
        'Flask', 'FastAPI', 'Spring Boot', 'ASP.NET Core', 'Ruby on Rails', 'SQL', 'PostgreSQL',
        'MySQL', 'MongoDB', 'Redis', 'Elasticsearch', 'REST APIs', 'GraphQL', 'gRPC', 'WebSockets',
        'Microservices', 'Monolithic Architecture', 'API Design', 'Authentication', 'Authorization',
        'OAuth', 'JWT', 'Docker', 'Kubernetes', 'AWS', 'Azure', 'Lambda Functions', 'Serverless',
        'Message Queues', 'RabbitMQ', 'Kafka', 'Database Design', 'Indexing', 'Query Optimization',
        'Caching', 'Git', 'Testing', 'Unit Testing', 'Integration Testing', 'Security', 'Performance Optimization',
    ],

    'mobile developer': [
        'React Native', 'Flutter', 'Swift', 'Kotlin', 'Java', 'Objective-C', 'Dart', 'iOS Development',
        'Android Development', 'Mobile UI/UX', 'Material Design', 'Human Interface Guidelines',
        'REST APIs', 'GraphQL', 'State Management', 'Redux', 'MobX', 'Provider', 'Bloc', 'Git',
        'Xcode', 'Android Studio', 'VS Code', 'App Store Deployment', 'Google Play Deployment',
        'Firebase', 'Push Notifications', 'In-App Purchases', 'Deep Linking', 'Mobile Analytics',
        'Crash Reporting', 'Testing', 'Unit Testing', 'UI Testing', 'Performance Optimization',
        'Debugging', 'Memory Management', 'Threading', 'Async Programming', 'SQLite', 'Realm',
        'Core Data', 'Responsive Layouts', 'Touch Gestures', 'Camera Integration', 'Location Services',
        'Bluetooth', 'Native Modules', 'Platform-Specific Code', 'Code Signing', 'CI/CD',
    ],

    'data scientist': [
        'Python', 'R', 'SQL', 'Machine Learning', 'Deep Learning', 'Statistics', 'Probability',
        'Linear Algebra', 'Calculus', 'TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'Pandas',
        'NumPy', 'SciPy', 'Matplotlib', 'Seaborn', 'Plotly', 'Data Visualization', 'Jupyter Notebooks',
        'Feature Engineering', 'Model Selection', 'Hyperparameter Tuning', 'Cross-Validation',
        'Regression', 'Classification', 'Clustering', 'Neural Networks', 'CNNs', 'RNNs', 'NLP',
        'Computer Vision', 'Time Series Analysis', 'A/B Testing', 'Hypothesis Testing', 'Big Data',
        'Spark', 'Hadoop', 'Data Cleaning', 'Data Preprocessing', 'Exploratory Data Analysis',
        'Model Deployment', 'MLOps', 'Git', 'Docker', 'Cloud Computing', 'Communication', 'Problem Solving',
    ],

    'data analyst': [
        'SQL', 'Python', 'R', 'Excel', 'Tableau', 'Power BI', 'Looker', 'Data Studio', 'Data Visualization',
        'Statistics', 'Descriptive Statistics', 'Inferential Statistics', 'Data Cleaning', 'Data Preprocessing',
        'ETL', 'Data Modeling', 'Reporting', 'Dashboard Creation', 'Google Analytics', 'Adobe Analytics',
        'A/B Testing', 'Hypothesis Testing', 'Business Intelligence', 'KPI Development', 'Metrics Analysis',
        'Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'SQL Joins', 'Subqueries', 'Window Functions',
        'Data Warehousing', 'Business Acumen', 'Communication', 'Presentation Skills', 'Problem Solving',
        'Critical Thinking', 'Attention to Detail', 'Time Management', 'Stakeholder Management',
        'Requirements Gathering', 'Data Storytelling', 'Excel Pivot Tables', 'VLOOKUP', 'Macros', 'VBA',
    ],

    'data engineer': [
        'Python', 'Java', 'Scala', 'SQL', 'Apache Spark', 'Apache Kafka', 'Apache Airflow', 'Hadoop',
        'Hive', 'Presto', 'ETL', 'ELT', 'Data Pipelines', 'Data Warehousing', 'Data Lakes', 'AWS',
        'S3', 'Redshift', 'Glue', 'EMR', 'Azure', 'Azure Data Factory', 'Synapse', 'Google Cloud',
        'BigQuery', 'Dataflow', 'Pub/Sub', 'Docker', 'Kubernetes', 'Git', 'Data Modeling',
        'Dimensional Modeling', 'Star Schema', 'Snowflake Schema', 'PostgreSQL', 'MySQL', 'MongoDB',
        'Cassandra', 'Redis', 'Elasticsearch', 'Data Quality', 'Data Governance', 'Performance Optimization',
        'Query Optimization', 'Indexing', 'Partitioning', 'Streaming Data', 'Batch Processing', 'CI/CD',
    ],

    'machine learning engineer': [
        'Python', 'C++', 'Java', 'TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'Machine Learning',
        'Deep Learning', 'Neural Networks', 'CNNs', 'RNNs', 'LSTMs', 'Transformers', 'GANs', 'NLP',
        'Computer Vision', 'Reinforcement Learning', 'Model Training', 'Model Optimization', 'Hyperparameter Tuning',
        'Feature Engineering', 'Model Deployment', 'MLOps', 'Docker', 'Kubernetes', 'AWS', 'SageMaker',
        'Azure ML', 'Google Cloud AI', 'Git', 'CI/CD', 'REST APIs', 'Model Serving', 'Model Monitoring',
        'A/B Testing', 'Statistics', 'Linear Algebra', 'Calculus', 'Probability', 'Data Structures',
        'Algorithms', 'Distributed Computing', 'Spark', 'GPU Programming', 'CUDA', 'Model Compression',
        'Quantization', 'Pruning', 'Transfer Learning', 'AutoML', 'Experiment Tracking', 'MLflow', 'Weights & Biases',
    ],

    'ai engineer': [
        'Python', 'TensorFlow', 'PyTorch', 'Keras', 'Machine Learning', 'Deep Learning', 'Neural Networks',
        'NLP', 'Natural Language Processing', 'BERT', 'GPT', 'Transformers', 'Computer Vision', 'CNNs',
        'Object Detection', 'Image Segmentation', 'Reinforcement Learning', 'Generative AI', 'GANs',
        'Diffusion Models', 'LLMs', 'Prompt Engineering', 'Fine-Tuning', 'RAG', 'Vector Databases',
        'Embeddings', 'AI Ethics', 'Responsible AI', 'Model Interpretability', 'XAI', 'Model Optimization',
        'Model Deployment', 'MLOps', 'Cloud Computing', 'AWS', 'Azure', 'Google Cloud', 'Docker',
        'Kubernetes', 'Git', 'Statistics', 'Mathematics', 'Linear Algebra', 'Calculus', 'Probability',
        'Research', 'Paper Reading', 'Experiment Design', 'Data Preprocessing', 'Feature Engineering',
    ],

    'product manager': [
        'Product Strategy', 'Product Vision', 'Roadmap Planning', 'Product Lifecycle', 'User Research',
        'User Personas', 'User Stories', 'Use Cases', 'Requirements Gathering', 'Prioritization',
        'Backlog Management', 'Data Analysis', 'SQL', 'Analytics Tools', 'Google Analytics', 'Mixpanel',
        'Amplitude', 'A/B Testing', 'Experimentation', 'Agile', 'Scrum', 'Kanban', 'Sprint Planning',
        'Stakeholder Management', 'Communication', 'Presentation Skills', 'Market Research', 'Competitive Analysis',
        'Customer Development', 'Wireframing', 'Mockups', 'Figma', 'Prototyping', 'UX Principles',
        'Metrics & KPIs', 'OKRs', 'Go-to-Market Strategy', 'Pricing Strategy', 'Feature Specification',
        'Technical Fluency', 'Problem Solving', 'Decision Making', 'Leadership', 'Negotiation', 'Conflict Resolution',
        'Product Marketing', 'Customer Feedback', 'Jira', 'Confluence', 'Asana', 'Trello',
    ],

    'project manager': [
        'Project Planning', 'Project Scheduling', 'Agile', 'Scrum', 'Kanban', 'Waterfall', 'Hybrid Methodologies',
        'Risk Management', 'Risk Assessment', 'Mitigation Strategies', 'Budget Management', 'Cost Estimation',
        'Resource Allocation', 'Resource Planning', 'Stakeholder Communication', 'Stakeholder Management',
        'Team Leadership', 'Team Building', 'Conflict Resolution', 'Negotiation', 'Microsoft Project',
        'Jira', 'Confluence', 'Asana', 'Trello', 'Monday.com', 'Timeline Management', 'Gantt Charts',
        'Critical Path Method', 'Earned Value Management', 'Change Management', 'Problem Solving',
        'Decision Making', 'Documentation', 'Reporting', 'Status Reports', 'Quality Assurance',
        'Process Improvement', 'Continuous Improvement', 'Communication', 'Presentation Skills', 'Time Management',
        'PMP Certification', 'PRINCE2', 'Lean', 'Six Sigma', 'Meeting Facilitation', 'Sprint Planning',
    ],

    'ui/ux designer': [
        'Figma', 'Adobe XD', 'Sketch', 'InVision', 'Wireframing', 'Prototyping', 'Mockups', 'User Research',
        'User Interviews', 'Surveys', 'User Personas', 'User Journey Mapping', 'Empathy Mapping', 'Usability Testing',
        'A/B Testing', 'Design Systems', 'Component Libraries', 'Typography', 'Color Theory', 'Visual Hierarchy',
        'Layout Design', 'Grid Systems', 'Responsive Design', 'Mobile Design', 'Web Design', 'Accessibility',
        'WCAG', 'ARIA', 'Inclusive Design', 'Information Architecture', 'Sitemaps', 'User Flows', 'Task Flows',
        'Interaction Design', 'Micro-interactions', 'Animation', 'Motion Design', 'HTML/CSS Basics', 'Design Thinking',
        'Agile/UX', 'Collaboration', 'Communication', 'Presentation Skills', 'Critique', 'Iteration', 'Problem Solving',
    ],

    'graphic designer': [
        'Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign', 'CorelDRAW', 'Affinity Designer', 'Figma',
        'Typography', 'Font Selection', 'Kerning', 'Leading', 'Color Theory', 'Color Harmony', 'Branding',
        'Brand Identity', 'Logo Design', 'Layout Design', 'Composition', 'Visual Hierarchy', 'Print Design',
        'Digital Design', 'Web Design', 'Social Media Graphics', 'Marketing Materials', 'Packaging Design',
        'Illustration', 'Vector Graphics', 'Raster Graphics', 'Image Editing', 'Photo Manipulation',
        'Creative Thinking', 'Conceptualization', 'Attention to Detail', 'Communication', 'Client Relations',
        'Presentation Skills', 'Time Management', 'Project Management', 'Portfolio Development', 'Trend Awareness',
        'Print Production', 'File Preparation', 'Color Profiles', 'Resolution', 'Bleed & Margins', 'Grid Systems',
    ],

    'web designer': [
        'HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'Mobile-First Design', 'Figma', 'Adobe XD',
        'Sketch', 'Photoshop', 'Illustrator', 'Wireframing', 'Prototyping', 'UI/UX Principles', 'Typography',
        'Color Theory', 'Layout Design', 'Grid Systems', 'Flexbox', 'CSS Grid', 'Animations', 'CSS Transitions',
        'WordPress', 'CMS', 'Webflow', 'Squarespace', 'Web Standards', 'W3C Guidelines', 'Accessibility',
        'WCAG', 'SEO Basics', 'Meta Tags', 'Performance Optimization', 'Image Optimization', 'Cross-browser Compatibility',
        'Browser DevTools', 'Version Control', 'Git', 'Collaboration', 'Communication', 'Client Relations',
        'Time Management', 'Problem Solving', 'Attention to Detail', 'Branding', 'Visual Design', 'User Experience',
    ],

    'devops engineer': [
        'Linux', 'Ubuntu', 'CentOS', 'Red Hat', 'Bash', 'Shell Scripting', 'Python', 'Go', 'Docker',
        'Docker Compose', 'Kubernetes', 'K8s', 'Helm', 'AWS', 'EC2', 'S3', 'ECS', 'EKS', 'Lambda',
        'Azure', 'Azure DevOps', 'Google Cloud', 'GKE', 'CI/CD', 'Jenkins', 'GitLab CI', 'GitHub Actions',
        'CircleCI', 'Travis CI', 'Terraform', 'Infrastructure as Code', 'Ansible', 'Puppet', 'Chef',
        'Configuration Management', 'Monitoring', 'Prometheus', 'Grafana', 'ELK Stack', 'Datadog', 'New Relic',
        'Git', 'GitOps', 'ArgoCD', 'Flux', 'Networking', 'DNS', 'Load Balancing', 'Nginx', 'Apache',
        'Security', 'SSL/TLS', 'Firewalls', 'VPN', 'Container Security', 'Performance Optimization', 'Troubleshooting',
    ],

    'cloud engineer': [
        'AWS', 'EC2', 'S3', 'VPC', 'IAM', 'Lambda', 'RDS', 'ECS', 'EKS', 'CloudFormation', 'Azure',
        'Azure VMs', 'Azure Storage', 'Azure AD', 'Azure Functions', 'Azure Kubernetes Service', 'Google Cloud',
        'Compute Engine', 'Cloud Storage', 'GKE', 'Cloud Functions', 'Docker', 'Kubernetes', 'Terraform',
        'Infrastructure as Code', 'Ansible', 'Cloud Architecture', 'Multi-Cloud', 'Hybrid Cloud', 'Networking',
        'VPC', 'Subnets', 'Security Groups', 'Load Balancers', 'CDN', 'CloudFront', 'Security', 'IAM',
        'Encryption', 'Compliance', 'CI/CD', 'Jenkins', 'GitHub Actions', 'Linux', 'Bash', 'Python',
        'Monitoring', 'CloudWatch', 'Azure Monitor', 'Cost Optimization', 'Reserved Instances', 'Spot Instances',
        'Automation', 'Disaster Recovery', 'Backup', 'High Availability', 'Scalability', 'Migration', 'Troubleshooting',
    ],

    'security engineer': [
        'Cybersecurity', 'Information Security', 'Network Security', 'Application Security', 'Cloud Security',
        'Penetration Testing', 'Ethical Hacking', 'Vulnerability Assessment', 'Security Auditing', 'Threat Modeling',
        'Risk Assessment', 'Encryption', 'Cryptography', 'SSL/TLS', 'PKI', 'Firewalls', 'IDS/IPS', 'SIEM',
        'Splunk', 'ELK Stack', 'Security Operations', 'Incident Response', 'Forensics', 'Malware Analysis',
        'Threat Intelligence', 'Threat Hunting', 'Compliance', 'GDPR', 'HIPAA', 'PCI DSS', 'ISO 27001',
        'NIST', 'Security Frameworks', 'Linux', 'Windows', 'Networking', 'TCP/IP', 'Python', 'Bash',
        'PowerShell', 'Metasploit', 'Burp Suite', 'Wireshark', 'Nmap', 'OWASP Top 10', 'Web Application Security',
        'API Security', 'Container Security', 'Kubernetes Security', 'Security Tools', 'Identity Management',
    ],

    'network engineer': [
        'Networking', 'TCP/IP', 'OSI Model', 'Routing', 'Switching', 'VLANs', 'BGP', 'OSPF', 'EIGRP',
        'RIP', 'Static Routing', 'Dynamic Routing', 'Firewalls', 'VPN', 'IPSec', 'SSL VPN', 'Network Security',
        'Access Control Lists', 'Cisco', 'Cisco IOS', 'Juniper', 'Fortinet', 'Palo Alto', 'Network Design',
        'Network Architecture', 'LAN', 'WAN', 'SD-WAN', 'Network Troubleshooting', 'Packet Analysis', 'Wireshark',
        'DNS', 'DHCP', 'NAT', 'Load Balancing', 'QoS', 'Traffic Shaping', 'Network Monitoring', 'SNMP',
        'SolarWinds', 'PRTG', 'Wireless Networking', 'Wi-Fi', 'Network Automation', 'Python', 'Ansible',
        'Documentation', 'Network Diagrams', 'Problem Solving', 'Communication', 'Project Management', 'Certifications',
    ],

    'system administrator': [
        'Linux', 'Ubuntu', 'CentOS', 'Red Hat', 'SUSE', 'Windows Server', 'Windows 10/11', 'Active Directory',
        'Group Policy', 'User Management', 'Networking', 'TCP/IP', 'DNS', 'DHCP', 'Firewalls', 'Bash',
        'Shell Scripting', 'PowerShell', 'Python', 'Virtualization', 'VMware', 'Hyper-V', 'VirtualBox',
        'Backup & Recovery', 'Disaster Recovery', 'Monitoring', 'Nagios', 'Zabbix', 'Security', 'Patch Management',
        'Antivirus', 'Troubleshooting', 'Hardware', 'Servers', 'Storage', 'SAN', 'NAS', 'Cloud Computing',
        'AWS', 'Azure', 'Automation', 'Ansible', 'Documentation', 'Ticketing Systems', 'Email Systems',
        'Exchange', 'Office 365', 'Database Management', 'MySQL', 'PostgreSQL', 'Performance Tuning', 'Capacity Planning',
    ],

    'database administrator': [
        'SQL', 'MySQL', 'PostgreSQL', 'Oracle', 'SQL Server', 'MongoDB', 'Cassandra', 'Redis', 'Database Design',
        'Normalization', 'Denormalization', 'ER Diagrams', 'Schema Design', 'Indexing', 'Query Optimization',
        'Performance Tuning', 'Execution Plans', 'Backup & Recovery', 'Point-in-Time Recovery', 'Replication',
        'Master-Slave', 'Master-Master', 'High Availability', 'Clustering', 'Sharding', 'Partitioning', 'Security',
        'User Management', 'Permissions', 'Encryption', 'Auditing', 'Monitoring', 'Database Monitoring Tools',
        'Troubleshooting', 'Data Migration', 'ETL', 'Data Integrity', 'Constraints', 'Triggers', 'Stored Procedures',
        'Functions', 'Views', 'Transactions', 'ACID', 'Concurrency', 'Locking', 'Cloud Databases', 'AWS RDS',
        'Azure SQL', 'Documentation', 'Disaster Recovery', 'Capacity Planning', 'Linux', 'Bash', 'Python',
    ],

    'quality assurance engineer': [
        'Manual Testing', 'Automated Testing', 'Test Automation', 'Selenium', 'WebDriver', 'Appium', 'Cypress',
        'Playwright', 'JUnit', 'TestNG', 'PyTest', 'Jest', 'Mocha', 'Test Planning', 'Test Strategy',
        'Test Cases', 'Test Scenarios', 'Test Scripts', 'Bug Tracking', 'Defect Management', 'Jira', 'Bugzilla',
        'TestRail', 'API Testing', 'Postman', 'REST Assured', 'SoapUI', 'Regression Testing', 'Smoke Testing',
        'Sanity Testing', 'Integration Testing', 'System Testing', 'UAT', 'Performance Testing', 'Load Testing',
        'Stress Testing', 'JMeter', 'LoadRunner', 'Agile', 'Scrum', 'CI/CD', 'Jenkins', 'Git', 'SQL',
        'Attention to Detail', 'Problem Solving', 'Analytical Skills', 'Communication', 'Documentation', 'Test Reports',
    ],

    'qa engineer': [
        'Manual Testing', 'Automated Testing', 'Selenium', 'WebDriver', 'Cypress', 'Playwright', 'Puppeteer',
        'Jest', 'Mocha', 'Chai', 'PyTest', 'Test Cases', 'Test Scenarios', 'Bug Reporting', 'Jira', 'Confluence',
        'API Testing', 'Postman', 'REST APIs', 'GraphQL Testing', 'Regression Testing', 'Smoke Testing',
        'Integration Testing', 'End-to-End Testing', 'Unit Testing', 'TDD', 'BDD', 'Cucumber', 'Gherkin',
        'CI/CD', 'GitHub Actions', 'GitLab CI', 'Jenkins', 'Agile', 'Scrum', 'Sprint Testing', 'Git',
        'Version Control', 'Test Automation Frameworks', 'Page Object Model', 'Data-Driven Testing',
        'Keyword-Driven Testing', 'Cross-Browser Testing', 'Mobile Testing', 'Responsive Testing', 'Accessibility Testing',
        'Performance Testing', 'Attention to Detail', 'Communication', 'Problem Solving', 'Documentation', 'SQL',
    ],

    'qa tester': [
        'Manual Testing', 'Test Cases', 'Test Execution', 'Bug Reporting', 'Defect Lifecycle', 'Regression Testing',
        'Smoke Testing', 'Sanity Testing', 'Exploratory Testing', 'Ad-hoc Testing', 'User Acceptance Testing',
        'Functional Testing', 'Non-Functional Testing', 'UI Testing', 'Usability Testing', 'Jira', 'Bugzilla',
        'TestRail', 'Test Management', 'Test Plans', 'Test Scenarios', 'Test Documentation', 'Requirements Analysis',
        'Agile', 'Scrum', 'Sprint Testing', 'Communication', 'Attention to Detail', 'Problem Solving',
        'Critical Thinking', 'Analytical Skills', 'API Testing', 'Postman', 'Mobile Testing', 'Web Testing',
        'Cross-Browser Testing', 'Responsive Testing', 'Database Testing', 'SQL', 'Basic Automation', 'Selenium Basics',
        'Git Basics', 'Version Control', 'Test Metrics', 'Test Reports', 'Collaboration', 'Team Player',
    ],

    'technical writer': [
        'Technical Writing', 'Documentation', 'API Documentation', 'User Guides', 'User Manuals', 'How-To Guides',
        'Tutorials', 'Release Notes', 'README Files', 'Knowledge Base Articles', 'Markdown', 'reStructuredText',
        'AsciiDoc', 'Git', 'GitHub', 'GitLab', 'Docs as Code', 'Static Site Generators', 'MkDocs', 'Docusaurus',
        'Sphinx', 'Jekyll', 'Hugo', 'Communication', 'Technical Communication', 'Audience Analysis', 'Information Architecture',
        'Content Organization', 'Attention to Detail', 'Research', 'Subject Matter Experts', 'Interviewing',
        'Editing', 'Proofreading', 'Grammar', 'Style Guides', 'Microsoft Style Guide', 'Google Developer Style Guide',
        'Content Management', 'CMS', 'Confluence', 'SharePoint', 'Screenshots', 'Screen Recording', 'Diagrams',
        'Flowcharts', 'UML', 'Lucidchart', 'Draw.io', 'Collaboration', 'Agile', 'Scrum', 'JIRA', 'Basic HTML/CSS',
    ],

    'scrum master': [
        'Scrum', 'Scrum Framework', 'Agile', 'Agile Methodologies', 'Kanban', 'Lean', 'Sprint Planning',
        'Sprint Review', 'Sprint Retrospective', 'Daily Standup', 'Backlog Management', 'Product Backlog',
        'Sprint Backlog', 'User Stories', 'Story Points', 'Velocity', 'Burndown Charts', 'Facilitation',
        'Meeting Facilitation', 'Stakeholder Management', 'Communication', 'Active Listening', 'Conflict Resolution',
        'Problem Solving', 'Impediment Removal', 'Coaching', 'Team Coaching', 'Agile Coaching', 'Mentoring',
        'Servant Leadership', 'Team Building', 'Team Dynamics', 'Jira', 'Confluence', 'Azure DevOps', 'Trello',
        'Miro', 'Metrics & Reporting', 'Agile Metrics', 'Team Performance', 'Continuous Improvement', 'Change Management',
        'Process Improvement', 'Collaboration', 'Cross-Functional Teams', 'Self-Organization', 'Empowerment', 'Motivation',
        'Transparency', 'Inspection', 'Adaptation', 'Scrum Values', 'CSM Certification', 'PSM Certification',
    ],

    'business analyst': [
        'Requirements Gathering', 'Requirements Analysis', 'Requirements Documentation', 'Elicitation Techniques',
        'User Stories', 'Use Cases', 'Acceptance Criteria', 'Business Process Modeling', 'BPMN', 'Process Mapping',
        'Workflow Analysis', 'Gap Analysis', 'Stakeholder Analysis', 'Stakeholder Management', 'Communication',
        'Data Analysis', 'SQL', 'Excel', 'Advanced Excel', 'Pivot Tables', 'VLOOKUP', 'Power Query', 'Tableau',
        'Power BI', 'Data Visualization', 'Documentation', 'Functional Specifications', 'Technical Specifications',
        'Jira', 'Confluence', 'Agile', 'Scrum', 'Waterfall', 'SDLC', 'Problem Solving', 'Critical Thinking',
        'Analytical Skills', 'Presentation Skills', 'Wireframing', 'Mockups', 'Figma', 'Lucidchart', 'Visio',
        'Process Improvement', 'Change Management', 'Testing', 'UAT', 'Test Cases', 'Project Management Basics',
    ],

    'marketing manager': [
        'Marketing Strategy', 'Brand Strategy', 'Campaign Management', 'Digital Marketing', 'Content Marketing',
        'Email Marketing', 'Social Media Marketing', 'SEO', 'Search Engine Optimization', 'SEM', 'PPC',
        'Google Ads', 'Facebook Ads', 'Instagram Ads', 'LinkedIn Ads', 'Marketing Analytics', 'Google Analytics',
        'Data Analysis', 'ROI Analysis', 'KPI Tracking', 'A/B Testing', 'Market Research', 'Competitive Analysis',
        'Customer Segmentation', 'Target Audience', 'Buyer Personas', 'Marketing Automation', 'HubSpot', 'Marketo',
        'Mailchimp', 'CRM', 'Salesforce', 'Budget Management', 'Budget Planning', 'Team Leadership', 'Team Management',
        'Vendor Management', 'Communication', 'Presentation Skills', 'Creativity', 'Copywriting', 'Content Creation',
        'Brand Management', 'Product Marketing', 'Go-to-Market Strategy', 'Event Marketing', 'PR', 'Influencer Marketing',
    ],

    'digital marketing specialist': [
        'Digital Marketing', 'SEO', 'Search Engine Optimization', 'On-Page SEO', 'Off-Page SEO', 'Technical SEO',
        'Keyword Research', 'SEM', 'PPC', 'Google Ads', 'Display Ads', 'Search Ads', 'Shopping Ads', 'Facebook Ads',
        'Instagram Ads', 'LinkedIn Ads', 'Twitter Ads', 'Social Media Marketing', 'Social Media Management',
        'Content Marketing', 'Content Creation', 'Copywriting', 'Email Marketing', 'Email Campaigns', 'Newsletter',
        'Marketing Automation', 'Google Analytics', 'GA4', 'Google Tag Manager', 'Facebook Pixel', 'Analytics',
        'Data Analysis', 'Reporting', 'A/B Testing', 'Conversion Rate Optimization', 'Landing Pages', 'WordPress',
        'CMS', 'HTML Basics', 'Canva', 'Adobe Creative Suite', 'Communication', 'Creativity', 'Strategy',
        'Campaign Management', 'Budget Management', 'ROI Analysis', 'Trend Analysis', 'Competitor Analysis',
    ],

    'seo specialist': [
        'SEO', 'Search Engine Optimization', 'On-Page SEO', 'Off-Page SEO', 'Technical SEO', 'Keyword Research',
        'Keyword Analysis', 'Competitive Analysis', 'SEO Audit', 'Site Audit', 'Link Building', 'Backlink Analysis',
        'Content Optimization', 'Meta Tags', 'Title Tags', 'Meta Descriptions', 'Header Tags', 'Schema Markup',
        'Structured Data', 'Google Analytics', 'GA4', 'Google Search Console', 'Bing Webmaster Tools', 'SEO Tools',
        'SEMrush', 'Ahrefs', 'Moz', 'Screaming Frog', 'Google PageSpeed Insights', 'Core Web Vitals', 'Page Speed',
        'Mobile Optimization', 'Mobile-First Indexing', 'Local SEO', 'Google My Business', 'HTML', 'CSS Basics',
        'JavaScript Basics', 'WordPress', 'Yoast SEO', 'Rank Math', 'Analytics', 'Reporting', 'Data Analysis',
        'Communication', 'Content Writing', 'Copywriting', 'Strategy', 'Algorithm Updates', 'Trend Awareness',
    ],

    'content writer': [
        'Content Writing', 'Copywriting', 'Creative Writing', 'Blog Writing', 'Article Writing', 'Web Content',
        'SEO Writing', 'SEO Content', 'Keyword Integration', 'Keyword Research', 'Research', 'Research Skills',
        'Fact-Checking', 'Editing', 'Proofreading', 'Grammar', 'Punctuation', 'Spelling', 'Style Guides',
        'AP Style', 'Chicago Style', 'Storytelling', 'Narrative', 'Engagement', 'Readability', 'Tone of Voice',
        'Brand Voice', 'Audience Understanding', 'WordPress', 'CMS', 'Content Management', 'Social Media Writing',
        'Email Writing', 'Newsletter Writing', 'Product Descriptions', 'Landing Pages', 'White Papers', 'Case Studies',
        'Creativity', 'Originality', 'Communication', 'Time Management', 'Deadline Management', 'Adaptability',
        'Versatility', 'Attention to Detail', 'Collaboration', 'Feedback Implementation', 'Google Docs', 'Microsoft Word',
    ],

    'sales manager': [
        'Sales Strategy', 'Sales Planning', 'Territory Management', 'Account Management', 'Key Account Management',
        'Team Leadership', 'Team Management', 'Coaching', 'Mentoring', 'Performance Management', 'Sales Training',
        'CRM', 'Salesforce', 'HubSpot', 'Pipedrive', 'Pipeline Management', 'Sales Forecasting', 'Quota Management',
        'Target Setting', 'Lead Generation', 'Prospecting', 'Cold Calling', 'Negotiation', 'Closing', 'Deal Closing',
        'Client Relations', 'Relationship Building', 'Customer Service', 'Communication', 'Presentation Skills',
        'Persuasion', 'Problem Solving', 'Objection Handling', 'Consultative Selling', 'Solution Selling', 'Value Selling',
        'B2B Sales', 'B2C Sales', 'Sales Metrics', 'Analytics', 'Reporting', 'Business Development', 'Market Analysis',
        'Competitive Analysis', 'Networking', 'Motivation', 'Time Management', 'Strategic Thinking', 'Microsoft Office',
    ],

    'customer success manager': [
        'Customer Success', 'Customer Relations', 'Customer Relationship Management', 'Account Management', 'Client Management',
        'Onboarding', 'Customer Onboarding', 'User Onboarding', 'Training', 'Customer Training', 'Product Knowledge',
        'Product Expertise', 'CRM', 'Salesforce', 'HubSpot', 'Zendesk', 'Intercom', 'Communication', 'Active Listening',
        'Empathy', 'Problem Solving', 'Conflict Resolution', 'Issue Resolution', 'Escalation Management', 'Retention',
        'Customer Retention', 'Churn Reduction', 'Upselling', 'Cross-Selling', 'Expansion', 'Account Growth',
        'Customer Advocacy', 'Customer Feedback', 'Surveys', 'NPS', 'CSAT', 'Analytics', 'Data Analysis', 'Metrics',
        'Customer Health Scores', 'Engagement Tracking', 'Reporting', 'Presentation Skills', 'Time Management',
        'Organization', 'Collaboration', 'Cross-Functional Collaboration', 'Relationship Building', 'Trust Building',
        'Strategic Thinking', 'Business Acumen', 'Consultative Approach', 'Proactive Support', 'Documentation',
    ],

    'hr manager': [
        'Human Resources', 'HR Management', 'Recruitment', 'Talent Acquisition', 'Sourcing', 'Screening', 'Interviewing',
        'Behavioral Interviewing', 'Selection', 'Offer Negotiation', 'Onboarding', 'Employee Onboarding', 'Orientation',
        'Employee Relations', 'Employee Engagement', 'Performance Management', 'Performance Reviews', 'Goal Setting',
        'Feedback', 'Coaching', 'Conflict Resolution', 'Mediation', 'Disciplinary Actions', 'HR Policies',
        'Policy Development', 'Compliance', 'Labor Law', 'Employment Law', 'FMLA', 'ADA', 'EEOC', 'Compensation',
        'Benefits', 'Benefits Administration', 'Payroll', 'HRIS', 'Workday', 'BambooHR', 'ADP', 'Training & Development',
        'Learning & Development', 'Career Development', 'Succession Planning', 'Workforce Planning', 'Organizational Development',
        'Change Management', 'Culture Building', 'Communication', 'Leadership', 'Strategic Planning', 'Analytics',
        'HR Metrics', 'Reporting', 'Microsoft Office', 'Excel', 'Confidentiality', 'Ethics',
    ],

    'financial analyst': [
        'Financial Analysis', 'Financial Modeling', 'Excel', 'Advanced Excel', 'Financial Statements', 'Income Statement',
        'Balance Sheet', 'Cash Flow Statement', 'Ratio Analysis', 'Profitability Ratios', 'Liquidity Ratios',
        'Valuation', 'DCF', 'Comparable Company Analysis', 'Precedent Transactions', 'Data Analysis', 'Statistical Analysis',
        'Forecasting', 'Financial Forecasting', 'Budgeting', 'Budget Analysis', 'Variance Analysis', 'Financial Reporting',
        'Management Reporting', 'Presentation Skills', 'SQL', 'Database Querying', 'Bloomberg Terminal', 'Capital IQ',
        'FactSet', 'Accounting', 'GAAP', 'IFRS', 'Corporate Finance', 'Investment Analysis', 'Risk Analysis',
        'Sensitivity Analysis', 'Scenario Analysis', 'Business Intelligence', 'Tableau', 'Power BI', 'VBA',
        'Python', 'R', 'Communication', 'Attention to Detail', 'Problem Solving', 'Critical Thinking',
        'Analytical Skills', 'Time Management', 'Deadline Management', 'Collaboration', 'PowerPoint',
    ],

    'accountant': [
        'Accounting', 'Bookkeeping', 'Financial Reporting', 'Financial Statements', 'Income Statement', 'Balance Sheet',
        'Cash Flow Statement', 'General Ledger', 'Journal Entries', 'Accounts Payable', 'Accounts Receivable',
        'Reconciliation', 'Bank Reconciliation', 'Account Reconciliation', 'Tax Preparation', 'Tax Filing',
        'Tax Compliance', 'Payroll', 'Payroll Processing', 'Excel', 'QuickBooks', 'Xero', 'Sage', 'SAP',
        'Oracle Financials', 'GAAP', 'Generally Accepted Accounting Principles', 'IFRS', 'Auditing', 'Internal Controls',
        'Compliance', 'Financial Analysis', 'Budget Preparation', 'Month-End Close', 'Year-End Close', 'Cost Accounting',
        'Variance Analysis', 'Fixed Assets', 'Depreciation', 'Accruals', 'Attention to Detail', 'Accuracy',
        'Problem Solving', 'Analytical Skills', 'Communication', 'Time Management', 'Ethics', 'Integrity',
        'Organization', 'Documentation', 'Microsoft Office', 'CPA', 'Certification',
    ],
}
